name: Deploy to Server

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: vpswest.westus.cloudapp.azure.com
        username: organic
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/organic/dev/fail2ban_lite
          sudo git config --global --add safe.directory /home/organic/dev/fail2ban_lite
          sudo git fetch origin main
          sudo git reset --hard origin/main
          sudo docker-compose pull && sudo docker-compose up -d --build --force-recreate --remove-orphans